# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

variables:
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'

jobs:

- template: Windows/cicd/templates/build-StringAccount-Windows.yml
  parameters:
    displayName: 'AgoraStringAccountWindows'
    workingDirectory: 'Windows/Agora-String-Account-Windows'
    scheme: 'Agora-String-Account-Windows'
    sdkurl: $(iOSRTCSDK)

