trigger:
- master

variables:
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'

jobs:

- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindows'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows'
    scheme: 'Agora-RTC-Hooking-API-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'

