trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

variables:
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'

jobs:

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraStringAccountWindows'
    workingDirectory: 'Windows/Agora-String-Account-Windows'
    scheme: 'Agora-String-Account-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'LargeGroupVideoChatWindows'
    workingDirectory: 'Windows/LargeGroupVideoChat-Windows'
    scheme: 'LargeGroupVideoChat-Windowss'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraOpenLive.sln'

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraScreenSharingWindows'
    workingDirectory: 'Windows/Agora-Screen-Sharing-Windows'
    scheme: 'Agora-Screen-Sharing-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'

- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindows'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows'
    scheme: 'Agora-RTC-Hooking-API-Windows'
    sdkurl: $(WindowsRTCSDK)
				solutionName: 'AgoraHooking.sln'
