trigger:
- master

variables:
  #WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_FULL.zip'
  ConnectionName: sbd021
  RepoName: sbd021
jobs:
- template: Windows/cicd/templates/build-Windows-vs2013.yml
  parameters:
    displayName: 'AgoraMediaSourceWindows'
    workingDirectory: 'Windows/Agora-Media-Source-Windows'
    scheme: 'Agora-Media-Source-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraMediaSource.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
#Windows Demo
- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraStringAccountWindows'
    workingDirectory: 'Windows/Agora-String-Account-Windows'
    scheme: 'Agora-String-Account-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'LargeGroupVideoChatWindows'
    workingDirectory: 'Windows/LargeGroupVideoChat-Windows'
    scheme: 'LargeGroupVideoChat-Windowss'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraOpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraScreenSharingWindows'
    workingDirectory: 'Windows/Agora-Screen-Sharing-Windows'
    scheme: 'Agora-Screen-Sharing-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

#hook demo
- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindows'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows'
    scheme: 'Agora-RTC-Hooking-API-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    connectionName: $(ConnectionName)
    userRepository: $(RepoName)/Advanced-Video
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindowskuwo'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows-kuwo'
    scheme: 'Agora-RTC-Hooking-API-Windows-kuwo'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    connectionName: $(ConnectionName)
    userRepository: $(RepoName)/Advanced-Video
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindowsyingyonghuyu'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows-yingyonghuyu'
    scheme: 'Agora-RTC-Hooking-API-Windows-yingyonghuyu'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    connectionName: $(ConnectionName)
    userRepository: $(RepoName)/Advanced-Video
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
